name: Publish Image to Docker Hub

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 1'

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Update Python packages
        run: |
          uv pip compile requirements.in > requirements.txt
      - name: Push some files inside the workflow run
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          echo "This is a dummy file." > dummy.txt

          git add dummy.txt
          git add requirements.txt
          git commit -m "Add requirements.txt and dummy file for testing"
      - name: Get changed files
        id: changes
        uses: tj-actions/changed-files@v35
        with:
          files: 'requirements.txt'
      - name: Create secret file from user and password
        run: | 
          echo "BITBUCKET_USER=${{ secrets.BITBUCKET_USER }}" > .env
          echo "BITBUCKET_PASSWORD=${{ secrets.BITBUCKET_PASSWORD }}" >> .env
      - name: Create volumes-docker's image
        if: steps.changes.outputs.any_changed == 'true'
        run: |
          docker buildx build --tag volumes:ploa2025 --secret id=secret,src=.env --build-arg relatorios_version=v0.7.64 --build-arg execucao_version=v0.5.22 --build-arg reest_version=v0.2.6 .
